### ISSUE TITLE
Linked package from global packages cannot find dependeces

### ISSUE THREAD

**Issue by martinstefanov** [iproduct/course-angular#1]
The webpack isn't working if it is liked from global packages. 
For me it is working if after link the module: `npm link webpack`  I run: `npm i`

For more details see:
http://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-doesn-t-find-their-dependencies

https://github.com/npm/npm/issues/10343

**Comment by iproduct** [comment]
See also: [`npm install` after `npm link` will "steal" dependencies from linked packages #10343](https://github.com/npm/npm/issues/10343)
